version: '3.9'

services:
  web:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      DOCKERIZED: "true"
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: OSu_DB
      POSTGRES_USER: simon
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
